name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 17

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.5.4

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - id: publish-to-central
        name: Publish to Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn -B -U \
            -Dgpg.passphrase="${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}" \
            release:prepare release:perform

#      - name: clean
#        run: |
#          sudo rm -rf $GITHUB_WORKSPACE/*
#          sudo rm -rf .git
#      - name: Checkout project
#        uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: "adopt"
#          java-version: 17
#          server-id: github
#      - name: Set up Maven
#        uses: stCarolas/setup-maven@v4.5
#        with:
#          maven-version: 3.5.4
#      - name: Configure Git user
#        run: |
#          git config user.email "actions@github.com"
#          git config user.name "GitHub Actions"
#
#
#      - name: Deploy new version
#        shell: bash
#        run: mvn -B -U release:prepare release:perform
